---
## 下载
- name: Download SQLServer2019 ENU
  win_shell: 
    .\{{sqlserver_name}}.exe /ACTION=Download /Q /MEDIATYPE=Advanced /MEDIAPATH=C:\temp
  args:
    chdir: C:\temp

## 解压
- name: unzip {{sqlserver_name}}
  win_shell:
    .\SQLEXPRADV_x64_ENU.exe /u /x:c:\temp\{{sqlserver_name}}
  args:
    chdir: C:\temp\

## 安装
- name: Install SQLServer2019
  win_shell:
    .\SETUP.exe /Q /IACCEPTSQLSERVERLICENSETERMS /ACTION=install /FEATURES=SQL,AS,RS,IS,Tools /INSTANCENAME=MSSQLSERVER /UpdateEnabled=False
  args:
    chdir: C:\temp\{{sqlserver_name}}